export const chapters = [
  [
    "Your first Python programs",
    "Je eerste Pythonprogramma’s",
    "Run, explain and write a short program with output and comments.",
    "Voer een kort programma met uitvoer en commentaar uit, leg het uit en schrijf het zelf.",
  ],
  [
    "Variables and values",
    "Variabelen en waarden",
    "Name, inspect and change text and numeric values.",
    "Geef tekst en getallen een naam, onderzoek ze en wijzig ze.",
  ],
  [
    "Calculations and changing values",
    "Berekeningen en veranderende waarden",
    "Explain each calculation and track updates in order.",
    "Leg elke berekening uit en volg wijzigingen op volgorde.",
  ],
  [
    "Building useful text output",
    "Bruikbare tekstuitvoer maken",
    "Combine text and values into readable messages.",
    "Combineer tekst en waarden tot leesbare berichten.",
  ],
  [
    "Asking for input",
    "Om invoer vragen",
    "Read answers, convert numbers and normalise simple commands.",
    "Lees antwoorden, zet getallen om en normaliseer eenvoudige opdrachten.",
  ],
  [
    "Comparisons and Boolean values",
    "Vergelijkingen en booleaanse waarden",
    "Predict comparisons and combine Boolean rules.",
    "Voorspel vergelijkingen en combineer booleaanse regels.",
  ],
  [
    "Making decisions",
    "Beslissingen nemen",
    "Choose one action and test the boundaries of each rule.",
    "Kies een actie en test de grenzen van elke regel.",
  ],
  [
    "Repeating with while",
    "Herhalen met while",
    "Control a repeated conversation and explain why it stops.",
    "Beheers een herhaald gesprek en leg uit waarom het stopt.",
  ],
  [
    "Writing small functions",
    "Kleine functies schrijven",
    "Separate a program into functions with clear inputs and results.",
    "Verdeel een programma in functies met duidelijke invoer en resultaten.",
  ],
  [
    "Handling mistakes and invalid input",
    "Fouten en ongeldige invoer afhandelen",
    "Recover from bad input and build a usable calculator.",
    "Herstel van verkeerde invoer en bouw een bruikbare rekenmachine.",
  ],
  [
    "Introducing lists",
    "Kennismaken met lijsten",
    "Store, access and change a collection of values.",
    "Bewaar, lees en wijzig een verzameling waarden.",
  ],
  [
    "Processing lists with loops",
    "Lijsten verwerken met lussen",
    "Summarise, search and filter a collection with a loop.",
    "Vat een verzameling samen, doorzoek haar en filter met een lus.",
  ],
  [
    "Tuples and multiple results",
    "Tuples en meerdere resultaten",
    "Unpack coordinates and the results of a function.",
    "Pak coördinaten en de resultaten van een functie uit.",
  ],
  [
    "Libraries and separate Python files",
    "Bibliotheken en aparte Pythonbestanden",
    "Use documented libraries and import your own helper module.",
    "Gebruik gedocumenteerde bibliotheken en importeer je eigen hulpmodule.",
  ],
  [
    "Drawing and interacting with Pygame",
    "Tekenen en interactie met Pygame",
    "Draw a scene and respond to input in a browser game.",
    "Teken een scène en reageer op invoer in een browserspel.",
  ],
  [
    "Movement and game rules",
    "Beweging en spelregels",
    "Combine controls, movement, collisions and scoring into Pong.",
    "Combineer besturing, beweging, botsingen en punten tot Pong.",
  ],
  [
    "More powerful list processing",
    "Meer mogelijkheden met lijsten",
    "Reshape, sort and process nested collections.",
    "Bewerk, sorteer en verwerk geneste verzamelingen.",
  ],
  [
    "Strings as data",
    "Strings als gegevens",
    "Inspect, clean, split and format text.",
    "Onderzoek, schoon op, splits en formatteer tekst.",
  ],
  [
    "Dictionaries and records",
    "Dictionaries en records",
    "Manage named records and handle missing information.",
    "Beheer records met benoemde velden en verwerk ontbrekende informatie.",
  ],
  [
    "Reading and writing text files",
    "Tekstbestanden lezen en schrijven",
    "Read and create inspectable files that survive another run.",
    "Lees en maak controleerbare bestanden die een volgende uitvoering behouden blijven.",
  ],
  [
    "CSV records",
    "CSV-records",
    "Read and write quoted, delimited tabular records.",
    "Lees en schrijf tabelgegevens met scheidingstekens en aanhalingstekens.",
  ],
  [
    "JSON and saved data",
    "JSON en opgeslagen gegevens",
    "Load, update and save structured data.",
    "Laad, wijzig en bewaar gestructureerde gegevens.",
  ],
  [
    "Classes and objects",
    "Klassen en objecten",
    "Group state and behaviour while keeping instances independent.",
    "Groepeer toestand en gedrag en houd instanties onafhankelijk.",
  ],
  [
    "Python on your computer",
    "Python op je computer",
    "Set up a local project and begin an idea of your own.",
    "Stel een lokaal project in en begin aan een eigen idee.",
  ],
];
